version: '3.9'

services:
  coop_letter_dev-main-db:
    container_name: coop_letter_dev-main-db
    image: postgres:13
    hostname: coop_letter_dev-main-db
    ports:
      - '5436:5432'
    restart: always
    volumes:
      - coop_letter_dev_main_db_data:/var/lib/postgresql/data
    environment:
      TZ: 'UTC'
      POSTGRES_DB: coop-letter
      POSTGRES_USER: coop-letter-user
      POSTGRES_PASSWORD: 90Lz1AHTsXe293F0WS4FRq
    networks:
      - coop_letter_net
  coop_letter_dev-redis:
    container_name: coop_letter_dev-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6376:6379
    command: redis-server --save 60 1 --requirepass 90Lz1AHTsXe293F0WS4FRq --loglevel warning
    networks:
      - coop_letter_net
volumes:
  coop_letter_dev_main_db_data:

networks:
  coop_letter_net:
    driver: bridge
